## Import NumPy

In [1]:
import numpy as np

## Create NumPy arrays

### Create following 1d arrays

```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([1., 1., 1., 1., 1.])

```


In [6]:
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr_list2 = np.arange(1, 100)
arr_list2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

### Create following 2d arrays

```
array([[31, 22, 48],
       [52, 33, 40],
       [72,  8, 37]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

```

In [29]:
np.array([[31, 22, 48],
       [52, 33, 40],
       [72,  8, 37]])

array([[31, 22, 48],
       [52, 33, 40],
       [72,  8, 37]])

In [30]:
np.zeros((4, 5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
arr_vec = np.arange(24)
arr_vec.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Generate arrays with random numbers

- 1d array with 10 numbers from random uniform distribution
- 1d array with 25 numbers from normal distribution
- 4 x 5 array from random integer in [0, 100]

In [32]:
np.random.rand(10)

array([0.25051976, 0.1242252 , 0.33880603, 0.86179508, 0.2888328 ,
       0.7598512 , 0.83073417, 0.25283111, 0.27609578, 0.7436006 ])

In [34]:
np.random.randn(25)

array([ 0.7746116 ,  1.48308838, -0.42915386, -0.79074516,  1.22557533,
       -0.49528014, -0.62743991,  0.07913322,  0.16702618,  0.55774225,
       -1.90114077, -0.85300437,  0.03059279,  0.4999538 , -0.8718288 ,
        0.71798183,  0.05770028, -0.90918719,  0.10169553,  0.66391635,
        1.03821408,  0.31567941, -0.34428912, -0.69803357, -0.30680786])

In [49]:
np.random.randint(0, 100, (4, 5))

array([[82, 54, 18,  2, 52],
       [89, 44, 46, 63, 51],
       [ 4, 53, 81, 33,  8],
       [11, 46, 31, 59, 60]])

## Array Indexing



### 1d array indexing 

- From the following array, extract the elements shown below 

In [51]:
arr_1d = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 
                   53, 54, 55, 56, 57, 58, 59, 60])

1. 
    ```
    array([41, 42, 43, 44])
    ```
1. 
    ```
    array([56, 57, 58, 59, 60])
    ```
1. 
    ```
    array([51, 52, 53])
    ```
1. 
    ```
    array([42, 55, 49])
    ```


In [54]:
arr_1d[:4]

array([41, 42, 43, 44])

In [56]:
arr_1d[-5:]

array([56, 57, 58, 59, 60])

In [59]:
arr_1d[arr_1d < 45]

array([41, 42, 43, 44])

In [63]:
arr_1d[10:13]

array([51, 52, 53])

In [69]:
arr_1d[(arr_1d < 54) & (arr_1d > 50)]

array([51, 52, 53])

In [70]:
arr_1d[[1, 14, 8 ]]

array([42, 55, 49])

### 2d array indexing

- Do the same task for the following 2d array


In [81]:
arr_2d = np.array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

Using indexing, generate the following sub-arrays

1. 
    ```
    array([[31, 32, 33, 34, 35],
          [41, 42, 43, 44, 45]])
    ```
1. 
    ```
    array([[11, 12],
          [21, 22],
          [31, 32],
          [41, 42]])    
    ```
1. 
    ```
    array([[32, 33],
           [42, 43]])
    ```
1. 
    ```
    array([[23, 25],
          [43, 45]])    
    ```


In [76]:
arr_2d[2:]

array([[31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [83]:
arr_2d[:,:2]

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [85]:
arr_2d[-2:,1:3]

array([[32, 33],
       [42, 43]])

In [89]:
arr_2d[[1,4]][: [3,5]]

IndexError: ignored

In [91]:
arr_int = np.array([-448,  754,  990,   18, -689,  641, -199,  -44, -557, -222,  -18,
       -687,  -69,  106,  821,  628, -427, -269, -624, -478,  886,  841,
        999,   99,  964, -312,   42,  186,  298,  170, -441,  761,  900,
       -207,  626, -322, -351,  169,  523, -131, -508,  181,  714,  171,
       -131,  525,  810, -173,  424, -265,  242,  313,   57,  423,  685,
        -16,  732,  372,  661,  654, -106,  443,  281, -125,  523,  476,
        525,  577,  938, -140,  333,  180, -348,  591, -135,  961,  805,
       -488, -422,  538, -433,  873,  568, -202, -181,  986,  769, -682,
       -645,  883, -529,  -27,  656,  153, -165, -242, -678,  635, -135,
        364])

For the array above, find the following numbers
 - The max/min number
 - Standard deviation of the array
 - Mean 


In [93]:
np.mean(arr_int)

181.73

In [95]:
np.min(arr_int)

-689

In [97]:
np.max(arr_int)

999

In [98]:
np.sqrt(arr_int)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan, 27.45906044, 31.46426545,  4.24264069,         nan,
       25.3179778 ,         nan,         nan,         nan,         nan,
               nan,         nan,         nan, 10.29563014, 28.65309756,
       25.05992817,         nan,         nan,         nan,         nan,
       29.76575213, 29.        , 31.60696126,  9.94987437, 31.04834939,
               nan,  6.4807407 , 13.6381817 , 17.2626765 , 13.03840481,
               nan, 27.58622845, 30.        ,         nan, 25.01999201,
               nan,         nan, 13.        , 22.86919325,         nan,
               nan, 13.45362405, 26.72077843, 13.07669683,         nan,
       22.91287847, 28.46049894,         nan, 20.59126028,         nan,
       15.55634919, 17.69180601,  7.54983444, 20.5669638 , 26.17250466,
               nan, 27.05549852, 19.28730152, 25.70992026, 25.57342371,
               nan, 21.04756518, 16.76305461,         nan, 22.86919325,
       21.81742423, 22.91287847, 24.0208243 , 30.62678566,      

## Array Operations (2d)


In [99]:
arr_normal = np.array([[-1.35589711,  0.32804138, -0.42081221, -0.26130734,  0.70162537,
        -2.74984249,  0.68124585, -0.1580792 , -0.14275744,  0.46342884,
         0.86430316, -0.07669887],
       [-0.74704059, -0.9071367 , -1.64174011,  0.03933122,  0.37675907,
         1.90269555,  0.44306442,  0.57069955, -0.28930021, -1.65834518,
         0.91165489, -0.24778658],
       [ 0.84422231, -2.61441156, -0.25364573,  0.75980507,  0.81245918,
         0.4495238 , -1.73419967,  0.06119128,  0.20092236, -0.02241897,
        -0.35468241, -1.10875505],
       [-1.2590743 , -1.798422  ,  0.29824561,  0.61399003, -2.84641582,
        -0.06309182, -0.86245245, -2.00527547, -1.36537977,  1.81020212,
         0.15409758,  0.77957902],
       [ 0.33642384,  1.6658424 ,  1.01517418, -0.94632536, -0.67836296,
        -1.58780134, -1.71699404,  0.19439649,  0.16351275, -2.08961948,
        -0.67480237, -0.98241524],
       [-0.97960876,  0.7256977 ,  0.2322489 , -0.79256359, -0.86636526,
         1.01071361,  0.06147106,  0.31257068,  0.54583426, -0.8035504 ,
         0.73390521,  0.05112845],
       [-0.17791452, -0.92611399,  0.27351997,  0.25378587,  0.78804843,
        -1.06393523,  2.65299826, -0.91232348, -2.93197926,  1.73152395,
         0.59431283, -0.10374418],
       [ 0.57609783,  0.51063139, -0.06848566,  2.65524085,  0.90236844,
        -0.63241958,  0.99904813, -0.6191799 ,  0.44955157, -1.99264591,
        -0.94398059, -0.68643509],
       [ 0.0329195 , -0.64513047,  0.46339352,  0.22950196,  1.03883248,
         2.09548912,  0.91148567, -1.05809727, -2.82315242, -1.24258192,
         0.32577142, -0.56579935],
       [ 0.76420142,  0.4468688 ,  0.69440669, -0.69501969,  0.99550496,
         0.04774205, -0.38475403, -0.34571432, -1.54386284,  2.93070093,
         0.55347872, -0.90081639]])

For the array above, find the following numbers
 - The max/min number 
    - in the entire array
    - in each row
    - in each column
 - Mean of 
    - the entire array
    - each row 
    - each column


In [101]:
np.max(arr_normal)

2.93070093

In [103]:
np.max(arr_normal, axis = 1)

array([0.86430316, 1.90269555, 0.84422231, 1.81020212, 1.6658424 ,
       1.01071361, 2.65299826, 2.65524085, 2.09548912, 2.93070093])

In [105]:
np.max(arr_normal, axis = 0)

array([0.84422231, 1.6658424 , 1.01517418, 2.65524085, 1.03883248,
       2.09548912, 2.65299826, 0.57069955, 0.54583426, 2.93070093,
       0.91165489, 0.77957902])

In [107]:
np.mean(arr_normal)

-0.1274502665833333

In [109]:
np.mean(arr_normal, axis = 0)

array([-0.19656704, -0.3214133 ,  0.05923052,  0.1856439 ,  0.12244539,
       -0.05909263,  0.10509132, -0.39598116, -0.7736611 , -0.0873306 ,
        0.21640584, -0.38417433])

In [110]:
np.mean(arr_normal, axis = 1)

array([-0.17722917, -0.10392872, -0.24666578, -0.54533311, -0.44174759,
        0.01929016,  0.01484822,  0.09581596, -0.10311398,  0.21356136])

# Control Sequences (optional)

## Programming FizzBuzz

Write a code for FizzBuzz. The definition of the program is:

> A program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”. (from [here](https://www.tomdalling.com/blog/software-design/fizzbuzz-in-too-much-detail/#:~:text=FizzBuzz%20is%20a%20very%20simple,numbers%20from%201%20to%20100))

##### Note:

- You can find numerous examples online, but please try by yourself :)
- The output is like:
    ```
    [1, 2, 'Fizz', 4, 'Buzz', 'Fizz', 7, 8, 'Fizz', 'Buzz', 11, 'Fizz', 13, 14,
     'FizzBuzz', 16, 17, 'Fizz', 19, 'Buzz', 'Fizz', 22, 23, 'Fizz', 'Buzz', 
     26, 'Fizz', 28, 29, 'FizzBuzz', 31, 32, 'Fizz', 34, 'Buzz', 'Fizz', 37, 
     38, 'Fizz', 'Buzz', 41, 'Fizz', 43, 44, 'FizzBuzz', 46, 47, 'Fizz', 49, 
     'Buzz', 'Fizz', 52, 53, 'Fizz', 'Buzz', 56, 'Fizz', 58, 59, 'FizzBuzz', 
     61, 62, 'Fizz', 64, 'Buzz', 'Fizz', 67, 68, 'Fizz', 'Buzz', 71, 'Fizz', 
     73, 74, 'FizzBuzz', 76, 77, 'Fizz', 79, 'Buzz', 'Fizz', 82, 83, 'Fizz', 
     'Buzz', 86, 'Fizz', 88, 89, 'FizzBuzz', 91, 92, 'Fizz', 94, 'Buzz', 
     'Fizz', 97, 98, 'Fizz']
    ```
- You need to know how to use `%` (Modulus) operator ([Link](https://www.tutorialspoint.com/python/python_basic_operators.htm))



In [114]:
arr_fizz = np.arange((0, 100)



TypeError: ignored